[tool.poetry]
name = "jar"
version = "0.1.0"
description = ""
authors = ["Pedro Guzmán <pedro.andres.guzman@ibm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs-material = "^9.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
